export const DOG_CHALLENGES = [
  "Photograph this keychain meeting a real hot dog.",
  "Find the brightest topping on the crawl.",
  "Include something Charlotte-red in the frame.",
  "Pose the keychain beside a local mural or public artwork.",
  "Capture the keychain in a reflection.",
  "Match the keychain with something the same color.",
  "Frame the keychain with a recognizable Charlotte building.",
  "Use perspective to make the little hot dog look enormous.",
  "Photograph the keychain beside your favorite drink.",
  "Show a menu item you would recommend to another crawler.",
  "Capture the most creative condiment swirl you can find.",
  "Find stripes, checks, or another bold pattern for the background.",
  "Bring two hot dog keychains together for a photo.",
  "Gather three or more hot dog keychains in one frame.",
  "Photograph the keychain beside a venue sign.",
  "Use warm evening or golden-hour light.",
  "Find a colorful neon sign for the background.",
  "Pose the keychain near an interesting doorway or entrance.",
  "Include a flower, tree, or other bit of Charlotte greenery.",
  "Find a funny but safe place for the keychain to sit.",
  "Make the keychain's shadow part of the picture.",
  "Photograph two or more hands holding the keychain, with permission.",
  "Make a cheers photo with any kind of drink.",
  "Include something bright yellow in the frame.",
  "Include something ketchup-red in the frame.",
  "Take the keychain to a Charlotte landmark.",
  "Find a piece of public art that deserves more attention.",
  "Look up and include an interesting ceiling or light fixture.",
  "Build the most colorful table scene you can.",
  "Take a clean top-down photo of the keychain and your food.",
  "Try a dramatic low-angle photo of the keychain.",
  "Create a perfectly symmetrical composition.",
  "Find three circles in the scene.",
  "Find three triangles in the scene.",
  "Include the number 704 somewhere in the picture.",
  "Find or create a crown for this Queen City hot dog.",
  "Include a Queen City reference in the background.",
  "Photograph the keychain near public transit, safely and while stationary.",
  "Include a bicycle or scooter in the background without blocking anyone.",
  "Photograph the keychain beside an interesting street sign.",
  "Pair the keychain with the best fries you can find.",
  "Show the most unusual hot dog topping you encounter.",
  "Find a vegetarian or vegan bite worth sharing.",
  "Celebrate a classic, no-frills hot dog.",
  "Find the spiciest-looking item on the crawl.",
  "Capture a sweet-and-savory food combination.",
  "Feature the logo of a local Charlotte business.",
  "Photograph a staff-recommended item; staff do not need to be pictured.",
  "Take a group photo where everyone pictured has agreed to be posted.",
  "Tell a story using only the keychain and objects, with no people pictured.",
  "Build a tiny scene around the keychain.",
  "Make the keychain look like it is reading the menu.",
  "Make the keychain look like it is placing an order.",
  "Introduce the keychain to a funny inanimate friend.",
  "Balance the keychain somewhere stable and safe.",
  "Show how the keychain looks clipped to a pocket or bag.",
  "Photograph the keychain beside another favorite keychain.",
  "Match the keychain with a pair of shoes in the frame.",
  "Include colorful socks or another playful clothing detail.",
  "Photograph the keychain with the crawl brochure.",
  "Show one completed section of the crawl brochure.",
  "Capture the feeling of your first stop.",
  "Capture the feeling of the midpoint of the crawl.",
  "Capture the feeling of the final stop.",
  "Take this hot dog into a neighborhood not yet shown on the map.",
  "Photograph the keychain at the farthest stop you visit today.",
  "Create a photo that tells a story without a caption.",
  "Get close and highlight an interesting texture.",
  "Create a scene that would look great in black and white.",
  "Show the energy of the event without photographing strangers' faces.",
  "Capture a quiet moment away from the busiest part of the crawl.",
  "Photograph the keychain near the liveliest scene you can frame respectfully.",
  "Create the best table-setting photo of the day.",
  "Line up ketchup, mustard, and one unexpected condiment.",
  "Make a small piece of napkin art and include the keychain.",
  "Photograph the most carefully presented plate you see.",
  "Take a photo on a patio or other outdoor space.",
  "Find a cozy indoor corner for the keychain.",
  "Feature one architectural detail people might usually miss.",
  "Zoom in on one detail from a mural or street artwork.",
  "Include today's weather in the story of the photo.",
  "Photograph the keychain under an umbrella, awning, or patch of shade.",
  "Use string lights, marquee lights, or another fun light source.",
  "Build the whole picture around your favorite color.",
  "Find ketchup red, mustard yellow, and hot-dog brown in one scene.",
  "Hide the keychain in the scene for a tiny visual scavenger hunt.",
  "Make the keychain the easiest thing in the picture to spot.",
  "Recreate the 🌭 emoji as closely as you can.",
  "Make a crown shape using safe objects already at your table.",
  "Find or form the letter C in the scene.",
  "Include the printed number of this hot dog somewhere in the picture.",
  "Choose one object that represents Charlotte to you.",
  "Make a silly, safe pose with everyone pictured giving permission.",
  "Capture a high five, with permission from everyone pictured.",
  "Show a welcoming feature that helps more people enjoy the venue.",
  "Find a quieter or lower-sensory corner and photograph the keychain there.",
  "Include a reusable cup, bottle, tote, or other reusable item.",
  "Capture a small moment of community kindness, with permission.",
  "Pass the keychain to someone new and take a photo together with permission.",
  "Create a celebratory finale photo for Hot Dog #100."
];

function numberFromCode(code = "") {
  const digitMatch = String(code).match(/(\d{1,3})/);
  if (digitMatch) return Number(digitMatch[1]);
  return [...String(code).toUpperCase()].reduce((total, character) => total + character.charCodeAt(0), 0) || 1;
}

export function getDogChallenge(dog, fallbackCode = "") {
  const rawNumber = Number(dog?.printed_number) || numberFromCode(dog?.public_code || fallbackCode);
  const challengeNumber = ((Math.max(1, rawNumber) - 1) % DOG_CHALLENGES.length) + 1;
  return {
    challengeNumber,
    prompt: DOG_CHALLENGES[challengeNumber - 1]
  };
}
